### ISSUE TITLE
possible to do a benchmark test using this package to show bytes allocation?

### ISSUE THREAD

**Issue by kolinfluence** [maurice2k/tcpserver#6]
possible to do a benchmark test using this package to show bytes allocation?

**Comment by maurice2k** [comment]
Makes no sense within tcpserver because it depends on what you do with it. It's a huge difference if you need to parse HTTP requests or if you have some kind of binary protocol.

It all boils down to how fast you can spin up worker "processes" (goroutines) and this is handled by Ultrapool (https://github.com/maurice2k/ultrapool) which has a benchmark included.
